/**
 * Types for Daily Priorities feature
 */

export type PrioritySection =
  | 'partner_success'
  | 'engineering'
  | 'launches'
  | 'pre_launch'
  | 'ops'
  | 'blocked';

export interface DailyPriority {
  id: string;
  active_date: string; // ISO date string (YYYY-MM-DD) - date task appears on
  created_date: string; // ISO date string (YYYY-MM-DD) - date task was created
  priority_order: number;
  section: PrioritySection;
  original_section: PrioritySection | null; // Section before being blocked
  agency_name: string | null;
  client_name: string | null;
  ticket_url: string | null;
  description: string | null;
  assignees: string[];
  completed: boolean;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
}

export interface PriorityComment {
  id: string;
  priority_id: string;
  comment: string;
  created_at: string;
  created_by: string | null;
}

export interface PriorityCommentInsert {
  priority_id: string;
  comment: string;
  created_by?: string | null;
}

export interface DailyPriorityInsert {
  active_date: string;
  created_date: string;
  priority_order: number;
  section: PrioritySection;
  agency_name?: string | null;
  client_name?: string | null;
  ticket_url?: string | null;
  description?: string | null;
  assignees?: string[];
  completed?: boolean;
  created_by?: string | null;
}

export interface DailyPriorityUpdate {
  priority_order?: number;
  section?: PrioritySection;
  original_section?: PrioritySection | null;
  agency_name?: string | null;
  client_name?: string | null;
  ticket_url?: string | null;
  description?: string | null;
  assignees?: string[];
  completed?: boolean;
  completed_at?: string | null;
  updated_by?: string | null;
}

export type RenewalStatus =
  | 'Awaiting Confirmation'
  | 'Confirmed - Pending Submission'
  | 'Renewal Submitted'
  | 'Not Renewing';

export interface CampaignRenewal {
  id: string;
  campaign_order_name: string;
  renewal_status: RenewalStatus;
  status_updated_at: string;
  status_updated_by: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CampaignRenewalInsert {
  campaign_order_name: string;
  renewal_status?: RenewalStatus;
  status_updated_by?: string | null;
  notes?: string | null;
}

export interface CampaignRenewalUpdate {
  renewal_status?: RenewalStatus;
  status_updated_by?: string | null;
  notes?: string | null;
}

export type IgnoreReason =
  | 'Integration not possible'
  | 'No ecomm to track'
  | 'Awareness-only campaign'
  | 'Campaign type doesn\'t support attribution (ie DOOH)';

export interface AutoGeneratedPriority {
  client_name: string;
  description: string;
  metric?: string | number;
  severity?: 'low' | 'medium' | 'high';
  // Additional pacing-specific fields
  daysLeft?: number;
  overallPacing?: number;
  yesterdayRatio?: number;
  // Renewal-specific fields
  renewalStatus?: RenewalStatus;
  renewalId?: string;
  // ROAS-specific fields
  isIgnored?: boolean;
  ignoreReason?: IgnoreReason;
}

export interface RoasAlertIgnore {
  id: string;
  campaign_order_name: string;
  ignored_at: string;
  ignored_by: string | null;
  ignore_reason: IgnoreReason;
  created_at: string;
  updated_at: string;
}

export interface RoasAlertIgnoreInsert {
  campaign_order_name: string;
  ignored_by?: string | null;
  ignore_reason: IgnoreReason;
}

export interface DailyPrioritiesView {
  date: string;
  manual_sections: {
    partner_success: DailyPriority[];
    engineering: DailyPriority[];
    launches: DailyPriority[];
    pre_launch: DailyPriority[];
    ops: DailyPriority[];
    blocked: DailyPriority[];
  };
  auto_sections: {
    renewals: AutoGeneratedPriority[];
    pacing: AutoGeneratedPriority[];
    roas: AutoGeneratedPriority[];
  };
}

export const SECTION_LABELS: Record<PrioritySection, string> = {
  partner_success: 'Partner Success',
  engineering: 'Engineering',
  launches: 'Launches',
  pre_launch: 'Pre-Launch',
  ops: 'Ops',
  blocked: 'Blocked'
};

export const SECTION_ORDER: PrioritySection[] = [
  'partner_success',
  'engineering',
  'launches',
  'pre_launch',
  'ops',
  'blocked'
];

export const RENEWAL_STATUS_LABELS: Record<RenewalStatus, string> = {
  'Awaiting Confirmation': 'Awaiting Confirmation',
  'Confirmed - Pending Submission': 'Confirmed - Pending Submission',
  'Renewal Submitted': 'Renewal Submitted',
  'Not Renewing': 'Not Renewing'
};

export const RENEWAL_STATUS_COLORS: Record<RenewalStatus, string> = {
  'Awaiting Confirmation': 'bg-gray-100 text-gray-800 border-gray-300',
  'Confirmed - Pending Submission': 'bg-blue-100 text-blue-700 border-blue-300',
  'Renewal Submitted': 'bg-green-100 text-green-700 border-green-300',
  'Not Renewing': 'bg-red-100 text-red-700 border-red-300'
};
