/**
 * RenewalsStatusPage - Page for tracking renewal process steps
 */

import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useRenewalStatusTracking } from '@/hooks/useRenewalStatusTracking';
import { useAutoGeneratedPriorities } from '@/hooks/useAutoGeneratedPriorities';
import { RenewalProcessStatus, RenewalType, RenewalStatusTrackingUpdate } from '@/types/daily-priorities';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { format, parseISO } from 'date-fns';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Plus, Trash2, ArrowLeft, CalendarIcon, Check, RefreshCw, ExternalLink, Pencil } from 'lucide-react';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Progress } from '@/components/ui/progress';
import { useSupabase } from '@/contexts/use-supabase';
import { CampaignDataRow } from '@/types/campaign';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';

const STATUS_OPTIONS: RenewalProcessStatus[] = [
  'Renewal Pending',
  'Recently Renewed',
  'Live',
  'Queued',
  'Paused - Client Request'
];

const RENEWAL_TYPE_OPTIONS: RenewalType[] = [
  'Extension',
  'Relaunch',
  'NOT Renewing'
];

export default function RenewalsStatusPage() {
  const navigate = useNavigate();
  const {
    trackingRecords,
    isLoading,
    createTrackingRecord,
    updateTrackingRecord,
    deleteTrackingRecord,
    hasTrackingRecord
  } = useRenewalStatusTracking();

  const { getCampaignData } = useSupabase();
  const [campaignData, setCampaignData] = useState<CampaignDataRow[]>([]);

  // Load campaign data for Upcoming Renewals
  useEffect(() => {
    const loadCampaignData = async () => {
      try {
        const data = await getCampaignData(undefined, undefined, () => {}, false);
        if (data.length > 0) {
          const transformedData = data.map(row => ({
            DATE: row.date,
            "CAMPAIGN ORDER NAME": row.campaign_order_name,
            IMPRESSIONS: row.impressions,
            CLICKS: row.clicks,
            REVENUE: row.revenue,
            SPEND: row.spend,
            TRANSACTIONS: row.transactions
          }));
          setCampaignData(transformedData);
        }
      } catch (error) {
        console.error('Failed to load campaign data:', error);
      }
    };
    loadCampaignData();
  }, [getCampaignData]);

  const autoSections = useAutoGeneratedPriorities(new Date(), campaignData);
  const upcomingRenewals = autoSections.renewals;

  const [newCampaignName, setNewCampaignName] = useState('');
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showSelectDialog, setShowSelectDialog] = useState(false);
  const [openDatePickers, setOpenDatePickers] = useState<Record<string, boolean>>({});
  const [activeTab, setActiveTab] = useState('open');
  const [editingTaskUrl, setEditingTaskUrl] = useState<Record<string, boolean>>({});
  const [taskUrlInputs, setTaskUrlInputs] = useState<Record<string, string>>({});

  const handleAddManual = () => {
    if (!newCampaignName.trim()) {
      return;
    }

    if (hasTrackingRecord(newCampaignName.trim())) {
      alert('This campaign already has a tracking record');
      return;
    }

    createTrackingRecord({
      campaign_name: newCampaignName.trim()
    });

    setNewCampaignName('');
    setShowAddDialog(false);
  };

  const handleAddFromRenewals = (campaignName: string, endDate?: string) => {
    if (hasTrackingRecord(campaignName)) {
      alert('This campaign already has a tracking record');
      return;
    }

    // Format end date to YYYY-MM-DD for date input
    let formattedEndDate: string | null = null;
    if (endDate) {
      try {
        // Parse the ISO date string and format it as YYYY-MM-DD
        const date = parseISO(endDate);
        if (!isNaN(date.getTime())) {
          formattedEndDate = format(date, 'yyyy-MM-dd');
        }
      } catch (e) {
        console.error('Error parsing end date:', e);
      }
    }

    createTrackingRecord({
      campaign_name: campaignName,
      renewal_date: formattedEndDate || null
    });

    setShowSelectDialog(false);
  };

  const handleCheckboxChange = (
    id: string,
    field: keyof RenewalStatusTrackingUpdate,
    checked: boolean
  ) => {
    updateTrackingRecord({
      id,
      updates: { [field]: checked }
    });
  };

  const handleStatusChange = (id: string, status: RenewalProcessStatus) => {
    updateTrackingRecord({
      id,
      updates: { status }
    });
  };

  const handleRenewalTypeChange = (id: string, renewalType: RenewalType) => {
    updateTrackingRecord({
      id,
      updates: { renewal_type: renewalType }
    });
  };

  const handleRenewalDateChange = (id: string, date: string) => {
    updateTrackingRecord({
      id,
      updates: { renewal_date: date || null }
    });
    // Close the popover after selecting a date
    setOpenDatePickers(prev => ({ ...prev, [id]: false }));
  };

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this tracking record?')) {
      deleteTrackingRecord(id);
    }
  };

  const handleMarkComplete = (id: string) => {
    updateTrackingRecord({
      id,
      updates: { 
        completed: true,
        completed_at: new Date().toISOString()
      }
    });
  };

  const handleReopen = (id: string) => {
    updateTrackingRecord({
      id,
      updates: { 
        completed: false,
        completed_at: null
      }
    });
  };

  // Filter and sort records based on completion status
  const openRecords = trackingRecords
    .filter(record => !record.completed)
    .sort((a, b) => {
      // Handle null/undefined dates - put them at the end
      if (!a.renewal_date && !b.renewal_date) return 0;
      if (!a.renewal_date) return 1;
      if (!b.renewal_date) return -1;
      // Sort by date ascending
      return new Date(a.renewal_date).getTime() - new Date(b.renewal_date).getTime();
    });
  
  const completedRecords = trackingRecords
    .filter(record => record.completed)
    .sort((a, b) => {
      // Handle null/undefined dates - put them at the end
      if (!a.renewal_date && !b.renewal_date) return 0;
      if (!a.renewal_date) return 1;
      if (!b.renewal_date) return -1;
      // Sort by date ascending
      return new Date(a.renewal_date).getTime() - new Date(b.renewal_date).getTime();
    });

  // Calculate completion percentage for a record
  const getCompletionPercentage = (record: typeof trackingRecords[0]) => {
    const steps = [
      record.project_kickoff_ticket_creation,
      record.bt_approval,
      record.coda_strategy,
      record.dashboard_update,
      record.dsp_update,
      record.pre_qa,
      record.post_qa
    ];
    const completed = steps.filter(Boolean).length;
    return Math.round((completed / steps.length) * 100);
  };

  // Get status badge variant
  const getStatusVariant = (status: RenewalProcessStatus) => {
    switch (status) {
      case 'Live':
        return 'default';
      case 'Recently Renewed':
        return 'default';
      case 'Queued':
        return 'secondary';
      case 'Paused - Client Request':
        return 'destructive';
      default:
        return 'outline';
    }
  };

  // Get renewal type badge variant
  const getRenewalTypeVariant = (type: RenewalType) => {
    switch (type) {
      case 'NOT Renewing':
        return 'destructive';
      case 'Relaunch':
        return 'secondary';
      default:
        return 'outline';
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 p-4 lg:p-6">
      <div className="max-w-[1600px] mx-auto">
        <Card className="shadow-sm">
          <CardHeader className="border-b bg-white">
            <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
              <div className="flex items-center gap-4">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => navigate('/')}
                  className="h-8 w-8 p-0"
                >
                  <ArrowLeft className="h-4 w-4" />
                </Button>
                <div>
                  <CardTitle className="text-xl">Renewals Status</CardTitle>
                  <p className="text-sm text-muted-foreground mt-1">
                    Track renewal process steps for campaigns
                  </p>
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
                  <DialogTrigger asChild>
                    <Button variant="outline" size="sm">
                      <Plus className="h-4 w-4 mr-2" />
                      Add Manually
                    </Button>
                  </DialogTrigger>
                  <DialogContent>
                    <DialogHeader>
                      <DialogTitle>Add Campaign</DialogTitle>
                    </DialogHeader>
                    <div className="space-y-4">
                      <Input
                        placeholder="Campaign Name"
                        value={newCampaignName}
                        onChange={(e) => setNewCampaignName(e.target.value)}
                        onKeyDown={(e) => {
                          if (e.key === 'Enter') {
                            handleAddManual();
                          }
                        }}
                      />
                      <Button onClick={handleAddManual} className="w-full">
                        Add Campaign
                      </Button>
                    </div>
                  </DialogContent>
                </Dialog>

                <Dialog open={showSelectDialog} onOpenChange={setShowSelectDialog}>
                  <DialogTrigger asChild>
                    <Button variant="outline" size="sm">
                      <Plus className="h-4 w-4 mr-2" />
                      Add from Upcoming Renewals
                    </Button>
                  </DialogTrigger>
                  <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
                    <DialogHeader>
                      <DialogTitle>Select from Upcoming Renewals</DialogTitle>
                      <p className="text-sm text-muted-foreground mt-1">
                        Showing campaigns with "Renewal Submitted" status
                      </p>
                    </DialogHeader>
                    <div className="space-y-2 mt-4">
                      {upcomingRenewals.length === 0 ? (
                        <p className="text-sm text-muted-foreground">No upcoming renewals available</p>
                      ) : (
                        (() => {
                          const filteredRenewals = upcomingRenewals
                            .filter(renewal => 
                              !hasTrackingRecord(renewal.client_name) && 
                              renewal.renewalStatus === 'Renewal Submitted'
                            )
                            .sort((a, b) => {
                              const daysA = a.daysLeft || 0;
                              const daysB = b.daysLeft || 0;
                              return daysA - daysB; // Sort ascending (fewest days left first)
                            });
                          
                          if (filteredRenewals.length === 0) {
                            return (
                              <p className="text-sm text-muted-foreground">
                                No upcoming renewals with "Renewal Submitted" status available
                              </p>
                            );
                          }
                          
                          return filteredRenewals.map((renewal) => (
                            <Button
                              key={renewal.client_name}
                              variant="outline"
                              className="w-full justify-start text-left"
                              onClick={() => handleAddFromRenewals(renewal.client_name, renewal.endDate)}
                            >
                              <span className="truncate">{renewal.client_name}</span>
                            </Button>
                          ));
                        })()
                      )}
                    </div>
                  </DialogContent>
                </Dialog>
              </div>
            </div>
          </CardHeader>
          <CardContent className="p-4 bg-gray-50">
            {isLoading ? (
              <div className="text-center py-12 text-muted-foreground">
                <p>Loading...</p>
              </div>
            ) : (
              <div className="w-full">
                <div className="flex gap-6 mb-6 border-b">
                  <button
                    onClick={() => setActiveTab('open')}
                    className={`pb-2 text-sm font-medium transition-colors ${
                      activeTab === 'open'
                        ? 'text-foreground border-b-2 border-foreground'
                        : 'text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    Open ({openRecords.length})
                  </button>
                  <button
                    onClick={() => setActiveTab('completed')}
                    className={`pb-2 text-sm font-medium transition-colors ${
                      activeTab === 'completed'
                        ? 'text-foreground border-b-2 border-foreground'
                        : 'text-muted-foreground hover:text-foreground'
                    }`}
                  >
                    Completed ({completedRecords.length})
                  </button>
                </div>
                {activeTab === 'open' && (
                  <>
                    {openRecords.length === 0 ? (
                      <div className="text-center py-12 text-muted-foreground">
                        <p className="mb-2">No open renewal tracking records.</p>
                        <p className="text-sm">Add a campaign to get started.</p>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        {openRecords.map((record) => {
                  const completion = getCompletionPercentage(record);
                  const isNotRenewing = record.renewal_type === 'NOT Renewing';
                  return (
                    <Card key={record.id} className="border shadow-sm hover:shadow-md transition-shadow">
                      <CardContent className="p-3">
                        <div className="flex gap-4 items-stretch">
                          <div className="flex-1 min-w-0 flex flex-col justify-between">
                            {/* Header Row: Campaign name, progress, dashboard task */}
                            <div className="flex items-center justify-between gap-1.5">
                              <div className="flex items-center gap-2 flex-1 min-w-0">
                                <h3 className="font-semibold text-sm">
                                  {record.campaign_name}
                                </h3>
                                <div className="flex items-center gap-2">
                                  <Progress value={completion} className="h-1.5 w-24" />
                                  <span className="text-xs text-muted-foreground whitespace-nowrap">{completion}%</span>
                                </div>
                              </div>
                              {editingTaskUrl[record.id] ? (
                                <div className="flex items-center gap-1">
                                  <Input
                                    type="url"
                                    placeholder="Task URL"
                                    value={taskUrlInputs[record.id] || record.task_url || ''}
                                    onChange={(e) => setTaskUrlInputs(prev => ({ ...prev, [record.id]: e.target.value }))}
                                    onBlur={() => {
                                      updateTrackingRecord({
                                        id: record.id,
                                        updates: { task_url: taskUrlInputs[record.id] || null }
                                      });
                                      setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                    }}
                                    onKeyDown={(e) => {
                                      if (e.key === 'Enter') {
                                        updateTrackingRecord({
                                          id: record.id,
                                          updates: { task_url: taskUrlInputs[record.id] || null }
                                        });
                                        setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                      } else if (e.key === 'Escape') {
                                        setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                        setTaskUrlInputs(prev => ({ ...prev, [record.id]: record.task_url || '' }));
                                      }
                                    }}
                                    className="h-7 text-xs w-48"
                                    autoFocus
                                  />
                                </div>
                              ) : (
                                <div className="flex items-center gap-1">
                                  {record.task_url ? (
                                    <>
                                      <a
                                        href={record.task_url}
                                        target="_blank"
                                        rel="noopener noreferrer"
                                        onClick={(e) => e.stopPropagation()}
                                        className="text-blue-600 hover:underline flex items-center gap-1 text-xs"
                                      >
                                        Dashboard Task
                                        <ExternalLink className="h-3 w-3" />
                                      </a>
                                      <button
                                        onClick={(e) => {
                                          e.stopPropagation();
                                          setEditingTaskUrl(prev => ({ ...prev, [record.id]: true }));
                                          setTaskUrlInputs(prev => ({ ...prev, [record.id]: record.task_url || '' }));
                                        }}
                                        className="text-muted-foreground hover:text-foreground"
                                        title="Edit task URL"
                                      >
                                        <Pencil className="h-3 w-3" />
                                      </button>
                                    </>
                                  ) : (
                                    <button
                                      onClick={(e) => {
                                        e.stopPropagation();
                                        setEditingTaskUrl(prev => ({ ...prev, [record.id]: true }));
                                        setTaskUrlInputs(prev => ({ ...prev, [record.id]: '' }));
                                      }}
                                      className="text-muted-foreground hover:text-foreground italic text-xs flex items-center gap-1"
                                      title="Add task URL"
                                    >
                                      No Dashboard task
                                      <Pencil className="h-3 w-3" />
                                    </button>
                                  )}
                                </div>
                              )}
                            </div>

                            {/* Checkboxes Row: Aligned to bottom */}
                            <div className="grid grid-cols-7 gap-2 w-full">
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-project`}
                              checked={record.project_kickoff_ticket_creation}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'project_kickoff_ticket_creation', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-project`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              Project & Kickoff
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-bt`}
                              checked={record.bt_approval}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'bt_approval', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-bt`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              BT/Approval
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-coda`}
                              checked={record.coda_strategy}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'coda_strategy', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-coda`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              Coda Strategy
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-dashboard`}
                              checked={record.dashboard_update}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'dashboard_update', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-dashboard`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              Dashboard Update
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-dsp`}
                              checked={record.dsp_update}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'dsp_update', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-dsp`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              DSP Update
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-preqa`}
                              checked={record.pre_qa}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'pre_qa', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-preqa`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              Pre QA
                            </label>
                          </div>
                          <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                            <Checkbox
                              id={`${record.id}-postqa`}
                              checked={record.post_qa}
                              disabled={isNotRenewing}
                              onCheckedChange={(checked) =>
                                handleCheckboxChange(record.id, 'post_qa', checked === true)
                              }
                              className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                            />
                            <label
                              htmlFor={`${record.id}-postqa`}
                              className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                            >
                              Post QA
                            </label>
                          </div>
                            </div>
                          </div>
                          {/* Right section: Renewal controls */}
                          <div className="flex items-start gap-3 flex-shrink-0 border-l pl-3">
                              <div className="flex flex-col gap-2">
                                <Popover 
                                  open={openDatePickers[record.id] || false}
                                  onOpenChange={(open) => setOpenDatePickers(prev => ({ ...prev, [record.id]: open }))}
                                >
                                  <PopoverTrigger asChild>
                                    <Button
                                      variant="outline"
                                      className="h-8 text-xs w-[180px] justify-start text-left font-normal"
                                    >
                                      <CalendarIcon className="mr-2 h-3 w-3" />
                                      {record.renewal_date ? format(parseISO(record.renewal_date), "MMM d, yyyy") : "Pick date"}
                                    </Button>
                                  </PopoverTrigger>
                                  <PopoverContent className="w-auto p-0" align="start">
                                    <Calendar
                                      mode="single"
                                      selected={record.renewal_date ? parseISO(record.renewal_date) : undefined}
                                      onSelect={(date) => {
                                        if (date) {
                                          handleRenewalDateChange(record.id, format(date, "yyyy-MM-dd"));
                                        }
                                      }}
                                      initialFocus
                                    />
                                  </PopoverContent>
                                </Popover>
                                <Select
                                  value={record.status}
                                  onValueChange={(value) => handleStatusChange(record.id, value as RenewalProcessStatus)}
                                >
                                  <SelectTrigger className="w-[180px] h-8 text-xs">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent className="max-h-[300px]">
                                    {STATUS_OPTIONS.map((status) => (
                                      <SelectItem key={status} value={status} className="text-xs">
                                        {status}
                                      </SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                                <Select
                                  value={record.renewal_type}
                                  onValueChange={(value) => handleRenewalTypeChange(record.id, value as RenewalType)}
                                >
                                  <SelectTrigger className="w-[180px] h-8 text-xs">
                                    <SelectValue />
                                  </SelectTrigger>
                                  <SelectContent className="max-h-[300px]">
                                    {RENEWAL_TYPE_OPTIONS.map((type) => (
                                      <SelectItem key={type} value={type} className="text-xs">
                                        {type}
                                      </SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              </div>
                              <div className="flex flex-col gap-1 self-center">
                                {!record.completed && (
                                  <Button
                                    variant="ghost"
                                    size="sm"
                                    onClick={() => handleMarkComplete(record.id)}
                                    className="h-8 w-8 p-0 hover:bg-green-50"
                                    title="Mark as complete"
                                  >
                                    <Check className="h-4 w-4 text-green-600" />
                                  </Button>
                                )}
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={() => handleDelete(record.id)}
                                  className="h-8 w-8 p-0 hover:bg-red-50"
                                  title="Delete"
                                >
                                  <Trash2 className="h-3.5 w-3.5 text-red-500" />
                                </Button>
                              </div>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                      </div>
                    )}
                  </>
                )}
                {activeTab === 'completed' && (
                  <>
                    {completedRecords.length === 0 ? (
                      <div className="text-center py-12 text-muted-foreground">
                        <p className="mb-2">No completed renewal tracking records.</p>
                      </div>
                    ) : (
                      <div className="space-y-4">
                        {completedRecords.map((record) => {
                        const completion = getCompletionPercentage(record);
                        const isNotRenewing = record.renewal_type === 'NOT Renewing';
                        return (
                          <Card key={record.id} className="border shadow-sm hover:shadow-md transition-shadow">
                            <CardContent className="p-3">
                              <div className="flex gap-4 items-stretch">
                                <div className="flex-1 min-w-0 flex flex-col justify-between">
                                  {/* Header Row: Campaign name, progress, dashboard task */}
                                  <div className="flex items-center justify-between gap-1.5">
                                    <div className="flex items-center gap-2 flex-1 min-w-0">
                                      <h3 className="font-semibold text-sm">
                                        {record.campaign_name}
                                      </h3>
                                      <div className="flex items-center gap-2">
                                        <Progress value={completion} className="h-1.5 w-24" />
                                        <span className="text-xs text-muted-foreground whitespace-nowrap">{completion}%</span>
                                      </div>
                                    </div>
                                    {editingTaskUrl[record.id] ? (
                                      <div className="flex items-center gap-1">
                                        <Input
                                          type="url"
                                          placeholder="Task URL"
                                          value={taskUrlInputs[record.id] || record.task_url || ''}
                                          onChange={(e) => setTaskUrlInputs(prev => ({ ...prev, [record.id]: e.target.value }))}
                                          onBlur={() => {
                                            updateTrackingRecord({
                                              id: record.id,
                                              updates: { task_url: taskUrlInputs[record.id] || null }
                                            });
                                            setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                          }}
                                          onKeyDown={(e) => {
                                            if (e.key === 'Enter') {
                                              updateTrackingRecord({
                                                id: record.id,
                                                updates: { task_url: taskUrlInputs[record.id] || null }
                                              });
                                              setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                            } else if (e.key === 'Escape') {
                                              setEditingTaskUrl(prev => ({ ...prev, [record.id]: false }));
                                              setTaskUrlInputs(prev => ({ ...prev, [record.id]: record.task_url || '' }));
                                            }
                                          }}
                                          className="h-7 text-xs w-48"
                                          autoFocus
                                        />
                                      </div>
                                    ) : (
                                      <div className="flex items-center gap-1">
                                        {record.task_url ? (
                                          <>
                                            <a
                                              href={record.task_url}
                                              target="_blank"
                                              rel="noopener noreferrer"
                                              onClick={(e) => e.stopPropagation()}
                                              className="text-blue-600 hover:underline flex items-center gap-1 text-xs"
                                            >
                                              Dashboard Task
                                              <ExternalLink className="h-3 w-3" />
                                            </a>
                                            <button
                                              onClick={(e) => {
                                                e.stopPropagation();
                                                setEditingTaskUrl(prev => ({ ...prev, [record.id]: true }));
                                                setTaskUrlInputs(prev => ({ ...prev, [record.id]: record.task_url || '' }));
                                              }}
                                              className="text-muted-foreground hover:text-foreground"
                                              title="Edit task URL"
                                            >
                                              <Pencil className="h-3 w-3" />
                                            </button>
                                          </>
                                        ) : (
                                          <button
                                            onClick={(e) => {
                                              e.stopPropagation();
                                              setEditingTaskUrl(prev => ({ ...prev, [record.id]: true }));
                                              setTaskUrlInputs(prev => ({ ...prev, [record.id]: '' }));
                                            }}
                                            className="text-muted-foreground hover:text-foreground italic text-xs flex items-center gap-1"
                                            title="Add task URL"
                                          >
                                            No Dashboard task
                                            <Pencil className="h-3 w-3" />
                                          </button>
                                        )}
                                      </div>
                                    )}
                                  </div>

                                  {/* Checkboxes Row: Aligned to bottom */}
                                  <div className="grid grid-cols-7 gap-2 w-full mt-auto">
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-project`}
                                    checked={record.project_kickoff_ticket_creation}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'project_kickoff_ticket_creation', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-project`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    Project & Kickoff
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-bt`}
                                    checked={record.bt_approval}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'bt_approval', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-bt`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    BT/Approval
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-coda`}
                                    checked={record.coda_strategy}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'coda_strategy', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-coda`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    Coda Strategy
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-dashboard`}
                                    checked={record.dashboard_update}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'dashboard_update', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-dashboard`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    Dashboard Update
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-dsp`}
                                    checked={record.dsp_update}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'dsp_update', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-dsp`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    DSP Update
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-preqa`}
                                    checked={record.pre_qa}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'pre_qa', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-preqa`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    Pre QA
                                  </label>
                                </div>
                                <div className="flex items-center gap-1.5 p-2 border rounded-md bg-gray-100 hover:bg-muted/50 transition-colors">
                                  <Checkbox
                                    id={`${record.id}-postqa`}
                                    checked={record.post_qa}
                                    disabled={isNotRenewing}
                                    onCheckedChange={(checked) =>
                                      handleCheckboxChange(record.id, 'post_qa', checked === true)
                                    }
                                    className={`h-3.5 w-3.5 ${isNotRenewing ? "opacity-50" : ""}`}
                                  />
                                  <label
                                    htmlFor={`${record.id}-postqa`}
                                    className={`text-sm cursor-pointer flex-1 ${isNotRenewing ? "opacity-50" : ""}`}
                                  >
                                    Post QA
                                  </label>
                                </div>
                              </div>
                                </div>
                                {/* Right section: Renewal controls */}
                                <div className="flex items-start gap-3 flex-shrink-0 border-l pl-3">
                                  <div className="flex flex-col gap-2">
                                    <Popover 
                                      open={openDatePickers[record.id] || false}
                                      onOpenChange={(open) => setOpenDatePickers(prev => ({ ...prev, [record.id]: open }))}
                                    >
                                      <PopoverTrigger asChild>
                                        <Button
                                          variant="outline"
                                          className="h-8 text-xs w-[180px] justify-start text-left font-normal"
                                        >
                                          <CalendarIcon className="mr-2 h-3 w-3" />
                                          {record.renewal_date ? format(parseISO(record.renewal_date), "MMM d, yyyy") : "Pick date"}
                                        </Button>
                                      </PopoverTrigger>
                                      <PopoverContent className="w-auto p-0" align="start">
                                        <Calendar
                                          mode="single"
                                          selected={record.renewal_date ? parseISO(record.renewal_date) : undefined}
                                          onSelect={(date) => {
                                            if (date) {
                                              handleRenewalDateChange(record.id, format(date, "yyyy-MM-dd"));
                                            }
                                          }}
                                          initialFocus
                                        />
                                      </PopoverContent>
                                    </Popover>
                                    <Select
                                      value={record.status}
                                      onValueChange={(value) => handleStatusChange(record.id, value as RenewalProcessStatus)}
                                    >
                                      <SelectTrigger className="w-[180px] h-8 text-xs">
                                        <SelectValue />
                                      </SelectTrigger>
                                      <SelectContent className="max-h-[300px]">
                                        {STATUS_OPTIONS.map((status) => (
                                          <SelectItem key={status} value={status} className="text-xs">
                                            {status}
                                          </SelectItem>
                                        ))}
                                      </SelectContent>
                                    </Select>
                                    <Select
                                      value={record.renewal_type}
                                      onValueChange={(value) => handleRenewalTypeChange(record.id, value as RenewalType)}
                                    >
                                      <SelectTrigger className="w-[180px] h-8 text-xs">
                                        <SelectValue />
                                      </SelectTrigger>
                                      <SelectContent className="max-h-[300px]">
                                        {RENEWAL_TYPE_OPTIONS.map((type) => (
                                          <SelectItem key={type} value={type} className="text-xs">
                                            {type}
                                          </SelectItem>
                                        ))}
                                      </SelectContent>
                                    </Select>
                                  </div>
                                  <div className="flex flex-col gap-1 self-center">
                                    <Button
                                      variant="ghost"
                                      size="sm"
                                      onClick={() => handleReopen(record.id)}
                                      className="h-8 w-8 p-0 hover:bg-blue-50"
                                      title="Re-open"
                                    >
                                      <RefreshCw className="h-4 w-4 text-blue-600" />
                                    </Button>
                                    <Button
                                      variant="ghost"
                                      size="sm"
                                      onClick={() => handleDelete(record.id)}
                                      className="h-8 w-8 p-0 hover:bg-red-50"
                                      title="Delete"
                                    >
                                      <Trash2 className="h-3.5 w-3.5 text-red-500" />
                                    </Button>
                                  </div>
                                </div>
                              </div>
                            </CardContent>
                          </Card>
                        );
                        })}
                      </div>
                    )}
                  </>
                )}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
